language: go

go:
    - "1.11.x"

branches:
  only:
    master

before_script:
    - go get -u -v github.com/gohugoio/hugo
    - npm install -g firebase-tools

script:
    - rm -rf public
    - hugo

after_success:
    - firebase deploy --token ${FIREBASE_TOKEN}
