baseurl = "https://adevjoe.com"
languageCode = "zh-cn"
title = "Joe's Blog"
theme = "hugo-tania"
paginate = 6

disqusShortname = "adevjoe"

[params]
  # Emoji will show before the blog title on site navbar.
  titleEmoji  = ""

  # Logo will show before the blog title on site navbar.
  titleLogo = ""

  # Enable float footnotes.
  # Default to true
  enableFootnotes = true
  siteName = "Joe's Blog"
  siteDesc = "Joe's Blog"
  author = "Joe"

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow = 10

  # Show your social information with icon on index bio with `_index.md` content.
  [params.socialOptions]
    dev-to = ""
    email = "adevjoe@gmail.com"
    facebook = ""
    github = "http://github.com/adevjoe"
    instagram = ""
    linkedin = ""
    medium = ""
    stack-overflow = ""
    steam = "https://steamcommunity.com/id/adevjoe"
    telegram = ""
    twitter = "https://twitter.com/adevjoe"
    twitch = ""
    whatsapp = ""
    rss = "/index.xml"

  # Comments settigns
  [params.comments]
    enabled = true
    provider = "disqus"

[menu]
[[menu.header]]
  name = "Articles"
  url = "/articles/"
[[menu.header]]
  name = "Categories"
  url = "/categories/"
#[[menu.header]]
#  name = "Tags"
#  url = "/tags/"
#[[menu.footer]]
#    name = "RSS"
#    url = "/index.xml"

[markup]
[markup.highlight]
  noClasses = false
  lineNos = true
[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
