name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Hugo Build
      uses: srt32/hugo-action@v0.0.3
    - name: Deploy on Firebase
      uses: w9jds/firebase-action@v1.0.1
      args: deploy --only hosting:prod
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
